### ISSUE TITLE
关于数据集的一点疑问

### ISSUE THREAD

**Issue by ZhangYizhao** [Ethan00Si/KuaiSAR#1]
作者您好，
关于KuaiSAR数据集中的rec_inter表格数据我有一点疑问，其中click这个行为到底指的是用户的什么行为呢，为什么可以作为划分正负样本的依据。

**Comment by Ethan00Si** [comment]
click的含义可以参考KuaiRand数据集(https://kuairand.com/ )中的注释：“A binary feedback signal. In the two-column UI, it indicates a click; In the single-column UI, it means valid_play: which equals 1 when: play_time_ms >= duration_ms if duration_ms <= 7,000 ms, or play_time_ms > 7,000 ms if duration_ms > 7,000 ms.” 。
推荐系统科研论文一般预测用户的隐式反馈，即用户是否点击物品，我们推荐用这个label作为implicit feedback的标签。短视频场景下"是否点击"的定义比较复杂，和具体业务相关，可以简单地将click当作implicit feedback。

**Comment by ZhangYizhao** [comment]
谢谢回复
